services:
  backend:
    build: .
    container_name: backend
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    networks:
      - app-net

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
